name: bookbuddy
description: Application de recommandation de livres intelligente et offline
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # État et navigation
  provider: ^6.1.1
  
  # Base de données (SQLite)
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # UI
  google_fonts: ^6.1.0
  flutter_rating_bar: ^4.0.1
  
  # Performance / Infos système
  battery_plus: ^5.0.2
  device_info_plus: ^9.1.1
  
  # Graphiques
  fl_chart: ^0.66.0
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/data/books.json